spring:
  application:
    name: MovieWeb
  datasource:
    url: "jdbc:mysql://localhost:3306/movieservice?useSSL=false&serverTimezone=UTC"
    username: root
    password: choinhanh12
  server:
    port: 8080
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
